name: Publish Python distributions to PyPI
on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt

    - name: Delete old packages
      run: >-
        if [ -f dist/*.tar.gz ] || [ -f dist/*.whl ]; then
          sudo rm -r dist/*.tar.gz dist/*.whl
        fi

    - name: Build a binary wheel and a source tarball
      run: >-
        python setup.py sdist bdist_wheel

    - name: Publish distribution to official PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
       password: ${{ secrets.PROD_PYPI_API_TOKEN }}